### ISSUE TITLE
Extra parameters to the validation url

### ISSUE THREAD

**Issue by db0** [jenkinsci/cas-plugin#6]
My CAS provider is requesting that I pass some extra parameters in the validation url (e.g. "?groups=internet"). 
Is there any possible way to do that using this plugin? I have root access to the jenkins systems so I can customize or reconfigure anything as needed.

I tried putting it in CAS Server URL variable, but from the logs I see that it didn't construct correctly.

**Comment by db0** [comment]
As far as I can see, [it is possible to pass custom parameters to the validation URL](https://github.com/apereo/java-cas-client/blob/1976710e2acd3a93750603d51a31a3ce8313a497/cas-client-core/src/main/java/org/jasig/cas/client/validation/AbstractUrlBasedTicketValidator.java#L64). I just need an interface to enter them. Unfortunately my java knowledge is pretty much non-existent so I cannot compile a pull request :(

**Comment by fcrespel** [comment]
Right now this plugin doesn't allow you to customize validation URL parameters, but it should be fairly straight-forward to implement. I'll give it a try and let you know.

**Comment by fcrespel** [comment]
A test build is available [here](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/cas-plugin/1.5.1-rc104.b9cd7d59b7e8/cas-plugin-1.5.1-rc104.b9cd7d59b7e8.hpi), to install it you can go to the Advanced tab of the Plugins page and upload it there. Then in the Security Realm config, click Advanced next to the Protocol selection and you'll find a textbox to specify "Custom validation URL parameters", i.e. `groups=internet`

Let me know if this works for you :-)

**Comment by db0** [comment]
Awesome! I will definitely try it out tomorrow first thing. Thanks so much for this fast response

**Comment by db0** [comment]
This works great, but it seems to have broken the JSON request. Now it always returns XML, because it seems the `&format=JSON` is never added to the validation URL.

**Comment by fcrespel** [comment]
Thanks for the feedback, here is a new [test build](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/cas-plugin/1.5.1-rc105.4dfd46798991/cas-plugin-1.5.1-rc105.4dfd46798991.hpi) that should fix this particular issue.

**Comment by db0** [comment]
This works! Brilliant. Thank you so much again!

**Comment by fcrespel** [comment]
CAS plugin version 1.6.0 is now released and includes this improvement.
