### ISSUE TITLE
Allow to combine two fields for fullName

### ISSUE THREAD

**Issue by db0** [jenkinsci/cas-plugin#8]
Currently my CAS provider does not return a fullName property. Instead they return only a 'firstName' and a 'lastName' property. I would like be able to combine these two properties to construct a fullname for Jenkins.

**Comment by fcrespel** [comment]
Here is a [new build](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/cas-plugin/1.5.1-rc110.018c239706f1/cas-plugin-1.5.1-rc110.018c239706f1.hpi) that now accepts `{{attribute}}` placeholders in the "Full Name Attribute" (and "Email Attribute") advanced protocol config (in addition to plain attribute names). So in your case, you could try `{{firstName}} {{lastName}}` for example. Let me know if this works for you.

**Comment by db0** [comment]
This works great! Thanks once more! :D

**Comment by fcrespel** [comment]
CAS plugin version 1.6.0 is now released and includes this improvement.
